<!DOCTYPE html>
<html>
<head>
<title><?php print $page_title; ?></title>
<meta charset="UTF-8">
<link rel="stylesheet" href="stylesheet.css" />
<script src="http://code.jquery.com/jquery-3.3.1.min.js"></script>
<script src="./scripts/.js"></script>
<script src="./scripts/login_valid.js"></script>

<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

</head>


<body>

<div class="container">

	<header>
	
    <h1><img src="./images/">Welcome to P&D</h1>      
    </header>
	</div>




<!-- end of header.inc -->
