<!-- start of navigation -->
<ul>
	<li><a href="index.php">Home</a></li>
	
	
	<li><a href="register.php">Register</a></li>
	<li><a href="login.php">Login</a></li>
	<li><a href="register_staff.php">Staff Register</a></li>
	<li><a href="login_staff.php">Staff Login</a></li>
	
	<li class="user"><a href='user_content.php'>user</a></li>
	
    <li class="logout"><a href='logout.php'>logout</a></li>

</ul>
<!-- end of navigation -->
